-- Fix for the existing expenses table.
-- The previous migration reached the index step, but the current table is missing `date`.
-- Run this whole script once in Supabase SQL Editor.

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  expense text not null,
  category text not null default 'Other',
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date,
  notes text,
  created_at timestamptz not null default now()
);

-- Bring an existing expenses table up to the schema expected by /api/expenses.
alter table public.expenses
  add column if not exists expense text,
  add column if not exists category text,
  add column if not exists amount numeric(12,2),
  add column if not exists date date,
  add column if not exists notes text,
  add column if not exists created_at timestamptz;

-- Backfill columns where the table already existed before this migration.
update public.expenses
set category = coalesce(category, 'Other')
where category is null;

update public.expenses
set date = coalesce(date, current_date)
where date is null;

update public.expenses
set created_at = coalesce(created_at, now())
where created_at is null;

-- Make required fields non-null only after backfill.
alter table public.expenses
  alter column expense set not null,
  alter column category set not null,
  alter column amount set not null,
  alter column date set not null,
  alter column created_at set not null;

create index if not exists expenses_date_created_idx
  on public.expenses (date desc, created_at desc);

alter table public.expenses enable row level security;

drop policy if exists "Organizers can read expenses" on public.expenses;
drop policy if exists "Organizers can insert expenses" on public.expenses;
drop policy if exists "Organizers can update expenses" on public.expenses;
drop policy if exists "Organizers can delete expenses" on public.expenses;

create policy "Organizers can read expenses"
  on public.expenses for select
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.approved = true
        and p.role in ('organizer','admin')
    )
  );

create policy "Organizers can insert expenses"
  on public.expenses for insert
  to authenticated
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.approved = true
        and p.role in ('organizer','admin')
    )
  );

create policy "Organizers can update expenses"
  on public.expenses for update
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.approved = true
        and p.role in ('organizer','admin')
    )
  )
  with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.approved = true
        and p.role in ('organizer','admin')
    )
  );

create policy "Organizers can delete expenses"
  on public.expenses for delete
  to authenticated
  using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.approved = true
        and p.role in ('organizer','admin')
    )
  );

grant select, insert, update, delete on public.expenses to authenticated;
